### ISSUE TITLE
"People Also Ask" Questions are being incorrectly counted

### ISSUE THREAD

**Issue by davidsandyds** [MartijnOud/SERP-counter#4]
The "People Also Ask" Questions are being incorrectly counted in the search results leading to incorrect ranking numbers.  Can you please fix this? Thanks!

**Comment by MartijnOud** [comment]
Thanks for letting me know! I added an extra check to make sure counted items are visible which should solve this issue. The extension has been updated (v1.2.4) and should update automatically (via chrome://extension you might be able to fetch an update earlier).

Please let me know if this issue persist.
