### ISSUE TITLE
Add option for number of results per page on searches

### ISSUE THREAD

**Issue by h5rdly** [MartijnOud/SERP-counter#8]
First of all all, much comfier with this addon, thank you!

I found SERP while looking for an addon that would add &num=xxx to the titlebar when searching, or some other technique, so that you can always get X results per page when searching, even if you're not signed in.

Would it be possible for you to add this option to SERP? That would make googling much smoother imo.

Thanks,
Eli

**Comment by MartijnOud** [comment]
Hi Eli, Glad to hear the extension is useful for you.

If I understand you correctly you want to always show 100 items per page in Google? Unfortunately this isn't something I can easily implement with my extension.

What might work is changing your default search engine in Chrome to include the exact options you like. If you navigate to `chrome://settings/search` you can add a new Google search engine and change the URL parameter to add the `num=xx` param.

**Comment by h5rdly** [comment]
Didn't know about that option, thanks!
